---
title: "280_emacs_notes.qmd "
author: "JR"
date: "5/22/2021"
pdf-engine: lualatex
format:
  html:
    toc: true
    html-math-method: katex
    theme: cosmo
    code-link: true
    code-overflow: wrap
    fig-align: center
    fig-cap-location: bottom
    fig-responsive: true
    embed-resources: true ## if standalone, all 1 file 
    css: css.styles
  pdf:
    documentclass: krantz
    keep-tex: true     ## each .tex from each .qmd file saved
                       ## SEE https://rfordatascience.slack.com/archives/CV1AGK1LY/p1687365502978109 
    include-in-header:
      text: |
        \usepackage{makeidx}
        \makeindex
    include-after-body:
      text: |
        \printindex
    fig-align: center
    fig-cap-location: bottom
output-dir: docs            ## NO indent, also _quarto.yml for entier project
editor_options: 
  chunk_output_type: console
execute: 
  error: true                   ## include errors in output
  warning: true
  collapse: true
  standalone: true
---

This document is about **emacs**, but written in quarto to practice quarto decorations
SEE: https://protesilaos.com/codelog/2022-01-31-learning-emacs/

## HELP
^h v  display-line-number \
^h a  evail   # any emacs/gnu topic? \
^h k  F10     # enter keystroke to see binding \

M-x describe-bindings
M-x describe-mode
```{r}
```

## LEARNING
emacswiki: (look for newbie) https://www.emacswiki.org/

daviwil:  emacs from scratch: videos + config
https://github.com/daviwil/emacs-from-scratch/tree/8c302a79bf5700f6ef0279a3daeeb4123ae8bd59

## EVIL
Read & re-read:  https://github.com/noctuid/evil-guide

## ELISP
Run lisp ?  or REPL:   open  ~/code/elisp_project/010_basic_elisp.el

^x p e  for eShell
^h i m Elisp RET (read manual) not working
- short guide: https://github.com/chrisdone-archive/elisp-guide?tab=readme-ov-file#programming-in-emacs-lisp
- practical: (REPL)  https://gigamonkeys.com/book/
- gnu elisp https://www.gnu.org/software/emacs/manual/html_node/eintr/index.html 
- Toretzky Gentle Common Lisp http://www.cs.cmu.edu/~dst/LispBook/



## Org mode
only in .org mode?
also M-x org-insert-link
[[nytimes.com]][nytimes]
	[['file:280_emacs_notes.qmd']][emacs notes]

## Watch Every Command ! 
M-x global-command-log-mode
M-x clm/open-command-log-buffer

Create a footnote: [^1]

[^1]: This is footnote one.

::: {.content-visible when-format="html"}
:::

```
<!--
{{< include _future_work.qmd >}}
-->

***
::: {.content-visible when-format="html"}
:::
***

##  PDF

::: {.content-visible when-format="pdf"}
TODO pdf - fix greater than equa
  pdf: 
    toc: false
    include-in-header: 
      text: |
        \usepackage[top=.5in, bottom=.5in, left=.7in, right=.5in]{geometry}
        \usepackage{amsmath,amssymb,amstext,amsfonts}
        \usepackage{lipsum}
:::



::: {.content-visible when-format="pdf"}
Will only appear in HTML.
\renewcommand{\familydefault}{\sfdefault}
\section{R Definitions \& Examples   (TERSE)}
\section{Manuals}
\\section(Definitions}
:::


