name: Render README

# This workflow will run on push or pull requests to the main branch
on:
  # schedule:
  #  - cron: '*/10 * * * *'
  push:
    branches: [main]

jobs:
  render:
    runs-on: ubuntu-latest

    permissions:
      contents: write  # Grant write permissions to the repository

    steps:
    - name: Checkout repository
      uses: actions/checkout@v4.2.2

    # Install Quarto CLI
    - name: Set up Quarto
      uses: quarto-dev/quarto-actions/setup@v2
      with:
        version: LATEST


    - uses: r-lib/actions/setup-r@v2
      with:
        use-public-rspm: true

    - uses: r-lib/actions/setup-r-dependencies@v2
      with:
        extra-packages: any::rcmdcheck
        needs: check

    - uses: r-lib/actions/check-r-package@v2
      with:
        upload-snapshots: true
        build_args: 'c("--no-manual","--compact-vignettes=gs+qpdf")'
 
      
    # Render the readme.qmd to README.md
    - name: Render Quarto document
      run: |
        quarto render readme.qmd --to gfm --output README.md

    # Commit and push changes to README.md
    - name: Commit README.md
      run: |
        git config --global user.name "github-actions[bot]"
        git config --global user.email "github-actions[bot]@users.noreply.github.com"
        git add README.md
        git commit -m "Update README.md from readme.qmd"
        git push
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}


    - name: Publish to Netlify
      run: |
        quarto publish readme.qmd
      env:
        NETLIFY_AUTH_TOKEN: ${{ secrets.NETLIFY_AUTH_TOKEN }}
        
    steps:
      - uses: actions/checkout@0ad4b8fadaa221de15dcec353f45205ec38ea70b

      - uses: ./setup-r
        with:
          use-public-rspm: true

      - uses: ./setup-r-dependencies
        with:
          extra-packages: any::rcmdcheck
          needs: check

      - uses: ./check-r-package
        with:
          upload-snapshots: true
          build_args: 'c("--no-manual","--compact-vignettes=gs+qpdf")'